Doc updated README
myhelmisaari/DD2480-Big-Brain-CI pull request #40
Opened 2020-02-07 09:53 UTC by myhelmisaari

Resolves #28 
Adds information about:
-  testing locally using gradle and building locally, using IntelliJ or the terminal
- ngrok: how to set it up and add it to a webhook
- more details on how the server is working

2020-02-07 12:51 UTC, hmellin97 commented
I think it looks good.

Small thing under _testing and building locally_
~~This~~ For windows machines you can use `gradlew test/build`.

2020-02-08 16:26 UTC, Mathiponds commented on README.md
> +* **Using the terminal:** first navigate to the the project folder, then use the command `./gradlew test`. To build the project locally use the command `./gradlew build`. For windows machines you can
The build command also run the tests. Maybe we can differantiate both like : To only run the test -> `gradle test` but to `gradle build` build and run the tests

2020-02-08 16:26 UTC, Mathiponds commented on README.md
> +If the build was successful there will be a new directory in the project named 'Build' that contains the generated classes. If it does not succeed the directory will not contain any generated classes
`build` instead of `Build`

2020-02-08 16:26 UTC, Mathiponds commented on README.md
> +1. Clones the project using `JGit`and saves it to a directory named 'assessment'.
It doesn't use `JGit` anymore. I'm only sending command line from Java
It saves to a directory named `assessmentDir`

2020-02-08 16:26 UTC, Mathiponds commented on README.md
> +1. Builds the cloned project and runs the tests defined in the project. This is done by executing the commands `./gradlew build` and `./gradlew test`.
It executes only the command `gradle build` and nothing else

2020-02-09 10:50 UTC, axelkennedal requested changes
What an excellent README! I wish we had this good documentation at my work 😄

2020-02-09 10:50 UTC, axelkennedal commented on README.md
> +CI is the second assignment in the course DD2480 Software Engineering Fundamentals. The goal of the assignment is to implement a continuous integration server that first clones a repository on GitHub
```suggestion
CI is the second assignment in the course DD2480 Software Engineering Fundamentals. The goal of the assignment is to implement a continuous integration server which first clones a repository on GitHub when there are any changes pushed to it, builds the project, runs the tests in the project and notifies the user of the results. 
```

2020-02-09 10:50 UTC, axelkennedal commented on README.md
> +This implementation of a CI-server is made with Java SDK 11 and IntelliJ; therefore make sure you have these installed. The project that uses the CI-server needs to have `Gradle` installed, due to it
```suggestion
This implementation of a CI-server is made with Java SDK 11 and IntelliJ; therefore make sure you have these installed. The project that uses the CI-server needs to have `Gradle` installed. For the project to build and run, there must exist a `build.gradle` file in the project, containing the dependencies needed.
```

2020-02-09 10:50 UTC, axelkennedal commented on README.md
> +There are two branches: `master` and `assessment`. The master branch contains the CI-server. The assessment branch is simulating a project with a main class and a simple test for it. The purpose of t
```suggestion
There are two main branches: `master` and `assessment`. The master branch contains the CI-server. The assessment branch is simulating a project with a main class and a simple test for it. The purpose of the assessment branch is to use it to test the functionality of the CI-server. 
```

2020-02-09 10:50 UTC, axelkennedal commented on README.md
> +* **Using the terminal:** first navigate to the the project folder, then use the command `./gradlew build`. This command builds and tests the project. If you only want to test and not build, use the
```suggestion
* **Using the terminal:** first navigate to the the project folder, then use the command `./gradlew build`. This command builds and tests the project. If you only want to test and not build, use the command `./gradlew test`. For windows machines you can use `gradlew test/build`.
```

2020-02-09 10:50 UTC, axelkennedal commented on README.md
> +To test the CI-server there is a specific branch prepared. Follow the following steps in the terminal to proceed. These steps assumes you have already cloned the repository.
```suggestion
To test the CI-server there is a specific branch prepared. Follow the steps below in the terminal to proceed. These steps assumes you have already cloned the repository.
```

2020-02-09 12:25 UTC, axelkennedal approved these changes

2020-02-09 12:26 UTC, merged